"""
Lumen ORM Base (2025)
=====================

Purpose
-------
Defines the shared SQLAlchemy Declarative Base and optional schema mixins used
throughout the Lumen data layer. All ORM entities in `src/database/models/`
must inherit from `Base`. This module provides:

- A unified metadata registry with strict naming conventions
- Optional mixins for timestamps and soft-deletes
- Lightweight helpers for UTC-safe defaults
- A clean, predictable foundation for Alembic migrations

Responsibilities
----------------
✓ Provide DeclarativeBase for all ORM entities  
✓ Enforce consistent SQL naming conventions across all tables  
✓ Supply mixins for common schema patterns  
✓ Maintain strict model-layer purity (no business logic)

Non-Responsibilities
--------------------
✗ No database access (handled by DatabaseService)  
✗ No domain logic (belongs to services)  
✗ No transactions or queries  
✗ No cross-layer imports  

Lumen 2025 Compliance
---------------------
- Models remain PURE DATA DEFINITIONS
- All logic is declarative (columns, relationships, metadata)
- No operational logic appears anywhere in `base.py`
- Type hints use modern SQLAlchemy Mapped[] syntax
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


# ============================================================================
# NAMING CONVENTIONS (Strongly recommended for Alembic)
# ============================================================================
# These ensure all autogenerated constraints have deterministic, human-readable
# identifiers. This prevents migration churn and improves traceability.

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": (
        "fk_%(table_name)s_%(column_0_name)s_"
        "%(referred_table_name)s"
    ),
    "pk": "pk_%(table_name)s",
}


# ============================================================================
# DECLARATIVE BASE
# ============================================================================

class Base(DeclarativeBase):
    """
    Root declarative base for all ORM models in Lumen.

    All data-model classes must inherit from this base. This ensures unified
    metadata, consistent naming conventions, and clean Alembic migration
    behavior.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def __repr__(self) -> str:
        """Lightweight repr showing primary key value if available."""
        table = getattr(self, "__table__", None)
        if table is not None:
            pk_columns = [c.name for c in table.columns if c.primary_key]
            if pk_columns:
                pk_name = pk_columns[0]
                pk_value = getattr(self, pk_name, None)
                return f"<{self.__class__.__name__}(id={pk_value})>"
        return f"<{self.__class__.__name__}>"


# ============================================================================
# OPTIONAL MIXINS
# ============================================================================

class TimestampMixin:
    """
    Adds created_at and updated_at fields to a model.

    Notes
    -----
    - Both fields are stored as timezone-aware UTC datetimes.
    - Uses SQLAlchemy server-defaults to ensure DB-level consistency.
    - Services should NOT override these manually except for domain-level audits.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        doc="Record creation timestamp (UTC).",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        doc="Record last update timestamp (UTC).",
    )


class SoftDeleteMixin:
    """
    Adds optional soft-delete semantics via a nullable deleted_at column.

    Notes
    -----
    - Records with deleted_at != NULL are considered soft-deleted.
    - Services must filter these out where appropriate.
    """

    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        doc="Soft-delete timestamp (NULL = active).",
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None


# ============================================================================
# UTILITY HELPERS
# ============================================================================

def utc_now() -> datetime:
    """
    Python-side helper for default=datetime values.

    Returns
    -------
    datetime (UTC, timezone-aware)
    """
    return datetime.now(timezone.utc)
